name: Provision Azure Tables

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group
        run: az group create --name "$RESOURCE_GROUP" --location "$LOCATION"
        env:
          RESOURCE_GROUP: ${{ secrets.AZURE_RG }}
          LOCATION: ${{ secrets.AZURE_LOCATION }}

      - name: Create storage account
        run: |
          az storage account create \
            --name "$STORAGE_ACCOUNT" \
            --resource-group "$RESOURCE_GROUP" \
            --location "$LOCATION" \
            --sku Standard_LRS \
            --kind StorageV2
        env:
          STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          RESOURCE_GROUP: ${{ secrets.AZURE_RG }}
          LOCATION: ${{ secrets.AZURE_LOCATION }}

      - name: Get connection string
        id: conn
        run: |
          az storage account show-connection-string \
            --name "$STORAGE_ACCOUNT" \
            --resource-group "$RESOURCE_GROUP" \
            --query connectionString -o tsv >> conn.txt
          echo "connection=$(cat conn.txt)" >> "$GITHUB_OUTPUT"
        env:
          STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          RESOURCE_GROUP: ${{ secrets.AZURE_RG }}

      - name: Create tables
        run: |
          az storage table create --name OrleansGrainState --connection-string "${{ steps.conn.outputs.connection }}"
          az storage table create --name TransactionalState --connection-string "${{ steps.conn.outputs.connection }}"
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ steps.conn.outputs.connection }}
